### ISSUE TITLE
Not working on iPad

### ISSUE THREAD

**Issue by jogios** [hansemannn/titanium-ios-document-picker#3]
Hi,
On iPhone works pretty well, but when execute on iPad throws an exception:
```
[ERROR] The application has crashed with an uncaught exception 'NSGenericException'.
[ERROR] Reason:
[ERROR] Your application has presented a UIDocumentMenuViewController (<UIDocumentMenuViewController: 0x7f8080415b50>). In its current trait environment, the modalPresentationStyle of a UIDocumentMenuViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.
[ERROR] Stack trace:
[ERROR] 0   CoreFoundation                      0x00000001091d21bb __exceptionPreprocess + 331
[ERROR] 1   libobjc.A.dylib                     0x0000000107fcd735 objc_exception_throw + 48
[ERROR] 2   UIKitCore                           0x0000000115b1fed1 -[UIPopoverPresentationController presentationTransitionWillBegin] + 3168
[ERROR] 3   UIKitCore                           0x0000000115b2987b __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 2495
[ERROR] 4   UIKitCore                           0x0000000115b26e6b __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 468
[ERROR] 5   UIKitCore                           0x00000001162370d2 _runAfterCACommitDeferredBlocks + 318
[ERROR] 6   UIKitCore                           0x0000000116225b2c _cleanUpAfterCAFlushAndRunDeferredBlocks + 384
[ERROR] 7   UIKitCore                           0x0000000116254efc _afterCACommitHandler + 135
[ERROR] 8   CoreFoundation                      0x0000000109136c27 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
[ERROR] 9   CoreFoundation                      0x00000001091310be __CFRunLoopDoObservers + 430
[ERROR] 10  CoreFoundation                      0x0000000109131751 __CFRunLoopRun + 1537
[ERROR] 11  CoreFoundation                      0x0000000109130e11 CFRunLoopRunSpecific + 625
[ERROR] 12  GraphicsServices                    0x000000010d17f1dd GSEventRunModal + 62
[ERROR] 13  UIKitCore                           0x000000011622b81d UIApplicationMain + 140
[ERROR] 14  poliConsultas                       0x00000001020e5d53 main + 115
[ERROR] 15  libdyld.dylib                       0x000000010a757575 start + 1
[ERROR] 16  ???                                 0x0000000000000001 0x0 + 1
```

**Comment by hansemannn** [comment]
The module is not optimized for iPad so far. You can extend it by following the following suggestion inside the above error:

>  You must provide either a sourceView and sourceRect or a barButtonItem.

**Comment by hansemannn** [comment]
I just added the change via https://github.com/hansemannn/titanium-ios-document-picker/commit/7bbf5d912d0bd4d46038cda6380b0982a17f66f0, give it a try!

**Comment by jogios** [comment]
Thank you, I'll fix it while you are doing the same, and sent a pull request #4 # before saw that you fixed it

Throw an error:
```
[ERROR] Script Error {
[ERROR]     column = 69;
[ERROR]     line = 57;
[ERROR]     message = "Can't find variable: UIModalPresentationPopover";
[ERROR]     sourceURL = "file:///Users/jogios/Library/Developer/CoreSimulator/Devices/75BF99FD-A39C-47F7-991D-FE81FB70F8DD/data/Containers/Bundle/Application/2A1DD6EA-9434-48EC-B727-8850EA290336/TiDocumentPicker.app/titanium-document-picker/index.js";
[ERROR]     stack = "    at show(/titanium-document-picker/index.js:57:69)\n    at (/app.js:12:40)";
[ERROR]     toJSON = "<KrollCallback: 0x600003adcb80>";
[ERROR] } 
```

**Comment by hansemannn** [comment]
Updated your PR and merged it. Let me know if it now works!

**Comment by jogios** [comment]
There are a mistake, I send a pull request #5 
```
[ERROR] An error occurred during build after 14s 374ms
[ERROR] Unexpected token (12:47)
```

**Comment by hansemannn** [comment]
Good to go now! :D
